from app.schemas.insurance import (
    PetInsurancePolicy,
    PetInsurancePolicyCreate,
    PetInsurancePolicyUpdate,
    InsuranceClaim,
    InsuranceClaimCreate,
    InsuranceClaimUpdate,
    InsuranceClaimDetail,
    InsurancePlanActiveUpdate,
    InsurancePlanCreate,
    InsurancePlanOut,
    InsuranceQuoteRequest,
    InsuranceQuoteOut,
    InsuranceSubscribeRequest,
)
