"""Init Mascotas

Revision ID: 55123be017cc
Revises: 
Create Date: 2026-02-28 13:49:06.148977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55123be017cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_pets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pet_name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_seen_location', sa.String(), nullable=False),
    sa.Column('date_lost', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_found', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_pets_id'), 'lost_pets', ['id'], unique=False)
    op.create_index(op.f('ix_lost_pets_pet_name'), 'lost_pets', ['pet_name'], unique=False)
    op.create_index(op.f('ix_lost_pets_user_id'), 'lost_pets', ['user_id'], unique=False)
    op.create_table('petfriendly_places',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_petfriendly_places_category'), 'petfriendly_places', ['category'], unique=False)
    op.create_index(op.f('ix_petfriendly_places_id'), 'petfriendly_places', ['id'], unique=False)
    op.create_index(op.f('ix_petfriendly_places_name'), 'petfriendly_places', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_petfriendly_places_name'), table_name='petfriendly_places')
    op.drop_index(op.f('ix_petfriendly_places_id'), table_name='petfriendly_places')
    op.drop_index(op.f('ix_petfriendly_places_category'), table_name='petfriendly_places')
    op.drop_table('petfriendly_places')
    op.drop_index(op.f('ix_lost_pets_user_id'), table_name='lost_pets')
    op.drop_index(op.f('ix_lost_pets_pet_name'), table_name='lost_pets')
    op.drop_index(op.f('ix_lost_pets_id'), table_name='lost_pets')
    op.drop_table('lost_pets')
    # ### end Alembic commands ###
