"""Add subscription fields

Revision ID: 6df753356d9e
Revises: 8db0ffc39e21
Create Date: 2026-03-04 01:57:56.343927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df753356d9e'
down_revision: Union[str, Sequence[str], None] = '8db0ffc39e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('has_active_subscription', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.alter_column('pets', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('pets', 'stripe_subscription_id')
    op.drop_column('pets', 'has_active_subscription')
    # ### end Alembic commands ###
