"""Enrich pet info

Revision ID: 8db0ffc39e21
Revises: 0eaacff2965a
Create Date: 2026-03-02 15:02:07.588501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db0ffc39e21'
down_revision: Union[str, Sequence[str], None] = '0eaacff2965a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('is_vaccinated', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('is_sterilized', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('is_dewormed', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('temperament', sa.Text(), nullable=True))
    op.add_column('pets', sa.Column('energy_level', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('social_cats', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('social_dogs', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('social_children', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('pets', sa.Column('microchip_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'microchip_number')
    op.drop_column('pets', 'weight_kg')
    op.drop_column('pets', 'social_children')
    op.drop_column('pets', 'social_dogs')
    op.drop_column('pets', 'social_cats')
    op.drop_column('pets', 'energy_level')
    op.drop_column('pets', 'temperament')
    op.drop_column('pets', 'is_dewormed')
    op.drop_column('pets', 'is_sterilized')
    op.drop_column('pets', 'is_vaccinated')
    # ### end Alembic commands ###
