"""Sync schema updates

Revision ID: 9a3ee10027cb
Revises: 55123be017cc
Create Date: 2026-03-02 11:06:33.387441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3ee10027cb'
down_revision: Union[str, Sequence[str], None] = '55123be017cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('owner_id', sa.String(), nullable=False))
    op.add_column('pets', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('adopted_from_listing_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_pets_clinic_id'), table_name='pets')
    op.create_index(op.f('ix_pets_adopted_from_listing_id'), 'pets', ['adopted_from_listing_id'], unique=False)
    op.create_index(op.f('ix_pets_id'), 'pets', ['id'], unique=False)
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=False)
    op.create_index(op.f('ix_pets_owner_id'), 'pets', ['owner_id'], unique=False)
    op.drop_column('pets', 'status')
    op.drop_column('pets', 'clinic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('clinic_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pets_owner_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_index(op.f('ix_pets_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_adopted_from_listing_id'), table_name='pets')
    op.create_index(op.f('ix_pets_clinic_id'), 'pets', ['clinic_id'], unique=False)
    op.drop_column('pets', 'adopted_from_listing_id')
    op.drop_column('pets', 'is_active')
    op.drop_column('pets', 'owner_id')
    # ### end Alembic commands ###
