"""Sync schema updates

Revision ID: a08e3bede7b3
Revises: 7e4084aa7c40
Create Date: 2026-03-02 11:06:57.469682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08e3bede7b3'
down_revision: Union[str, Sequence[str], None] = '7e4084aa7c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###
