"""add index to product is_active and is_approved

Revision ID: d3cceadb380a
Revises: 9189bf46d2f2
Create Date: 2026-03-04 21:37:50.750428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cceadb380a'
down_revision: Union[str, Sequence[str], None] = '9189bf46d2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_approved'), 'products', ['is_approved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_approved'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    # ### end Alembic commands ###
