"""Add is_approved to Clinics and Vets

Revision ID: bb8ae37ea53d
Revises: 35e2fa67254e
Create Date: 2026-03-02 14:48:50.104851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8ae37ea53d'
down_revision: Union[str, Sequence[str], None] = '35e2fa67254e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('veterinarians', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veterinarians', 'is_approved')
    op.drop_column('clinics', 'is_approved')
    # ### end Alembic commands ###
