"""Add performance indexes

Revision ID: f0046c41e344
Revises: 663e7ae4489d
Create Date: 2026-03-04 13:13:55.821384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0046c41e344'
down_revision: Union[str, Sequence[str], None] = '663e7ae4489d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_clinic_schedules_day_of_week'), 'clinic_schedules', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_clinic_schedules_is_active'), 'clinic_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_clinic_services_is_active'), 'clinic_services', ['is_active'], unique=False)
    op.create_index(op.f('ix_clinics_is_approved'), 'clinics', ['is_approved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinics_is_approved'), table_name='clinics')
    op.drop_index(op.f('ix_clinic_services_is_active'), table_name='clinic_services')
    op.drop_index(op.f('ix_clinic_schedules_is_active'), table_name='clinic_schedules')
    op.drop_index(op.f('ix_clinic_schedules_day_of_week'), table_name='clinic_schedules')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    # ### end Alembic commands ###
