"""add_logo_photo_reviews

Revision ID: f4774c469062
Revises: bb8ae37ea53d
Create Date: 2026-03-04 10:16:42.629236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4774c469062'
down_revision: Union[str, Sequence[str], None] = 'bb8ae37ea53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_reviews',
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_reviews_clinic_id'), 'clinic_reviews', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_reviews_user_id'), 'clinic_reviews', ['user_id'], unique=False)
    op.add_column('clinics', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('veterinarians', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veterinarians', 'photo_url')
    op.drop_column('clinics', 'logo_url')
    op.drop_index(op.f('ix_clinic_reviews_user_id'), table_name='clinic_reviews')
    op.drop_index(op.f('ix_clinic_reviews_clinic_id'), table_name='clinic_reviews')
    op.drop_table('clinic_reviews')
    # ### end Alembic commands ###
