"""Add medical records rules and prescriptions

Revision ID: ff52b4db4eb2
Revises: f0046c41e344
Create Date: 2026-03-04 15:10:51.125384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff52b4db4eb2'
down_revision: Union[str, Sequence[str], None] = 'f0046c41e344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('medical_record_id', sa.String(length=36), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency_hours', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_medical_record_id'), 'prescriptions', ['medical_record_id'], unique=False)
    op.create_table('medication_reminders',
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('remind_at', sa.String(length=50), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_reminders_pet_id'), 'medication_reminders', ['pet_id'], unique=False)
    op.create_index(op.f('ix_medication_reminders_prescription_id'), 'medication_reminders', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_medication_reminders_remind_at'), 'medication_reminders', ['remind_at'], unique=False)
    op.create_index(op.f('ix_medication_reminders_sent'), 'medication_reminders', ['sent'], unique=False)
    op.add_column('medical_records', sa.Column('appointment_id', sa.String(length=36), nullable=False))
    op.add_column('medical_records', sa.Column('vet_id', sa.String(length=36), nullable=True))
    op.add_column('medical_records', sa.Column('temperature_c', sa.Float(), nullable=True))
    op.add_column('medical_records', sa.Column('clinical_notes', sa.Text(), nullable=True))
    op.add_column('medical_records', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('medical_records', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('medical_records', 'clinic_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medical_records', 'diagnosis',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_index(op.f('ix_medical_records_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_veterinarian_id'), table_name='medical_records')
    op.create_index(op.f('ix_medical_records_appointment_id'), 'medical_records', ['appointment_id'], unique=True)
    op.create_foreign_key(None, 'medical_records', 'clinics', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'medical_records', 'appointments', ['appointment_id'], ['id'])
    op.create_foreign_key(None, 'medical_records', 'veterinarians', ['vet_id'], ['id'])
    op.drop_column('medical_records', 'veterinarian_id')
    op.drop_column('medical_records', 'treatment')
    op.drop_column('medical_records', 'date')
    op.drop_column('medical_records', 'notes')
    op.drop_column('medical_records', 'reason_for_visit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('reason_for_visit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('medical_records', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('treatment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('veterinarian_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_index(op.f('ix_medical_records_appointment_id'), table_name='medical_records')
    op.create_index(op.f('ix_medical_records_veterinarian_id'), 'medical_records', ['veterinarian_id'], unique=False)
    op.create_index(op.f('ix_medical_records_id'), 'medical_records', ['id'], unique=False)
    op.alter_column('medical_records', 'diagnosis',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('medical_records', 'clinic_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('medical_records', 'updated_at')
    op.drop_column('medical_records', 'created_at')
    op.drop_column('medical_records', 'clinical_notes')
    op.drop_column('medical_records', 'temperature_c')
    op.drop_column('medical_records', 'vet_id')
    op.drop_column('medical_records', 'appointment_id')
    op.drop_index(op.f('ix_medication_reminders_sent'), table_name='medication_reminders')
    op.drop_index(op.f('ix_medication_reminders_remind_at'), table_name='medication_reminders')
    op.drop_index(op.f('ix_medication_reminders_prescription_id'), table_name='medication_reminders')
    op.drop_index(op.f('ix_medication_reminders_pet_id'), table_name='medication_reminders')
    op.drop_table('medication_reminders')
    op.drop_index(op.f('ix_prescriptions_medical_record_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    # ### end Alembic commands ###
