"""add index to status columns

Revision ID: 1ecb5e96c930
Revises: 4d5c6394b7b8
Create Date: 2026-03-04 21:25:21.085283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecb5e96c930'
down_revision: Union[str, Sequence[str], None] = '4d5c6394b7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_adoption_listings_is_approved'), 'adoption_listings', ['is_approved'], unique=False)
    op.create_index(op.f('ix_adoption_listings_status'), 'adoption_listings', ['status'], unique=False)
    op.create_index(op.f('ix_adoption_requests_status'), 'adoption_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoption_requests_status'), table_name='adoption_requests')
    op.drop_index(op.f('ix_adoption_listings_status'), table_name='adoption_listings')
    op.drop_index(op.f('ix_adoption_listings_is_approved'), table_name='adoption_listings')
    # ### end Alembic commands ###
