"""Enrich adoption pet info

Revision ID: 4d5c6394b7b8
Revises: ff3b5efad75c
Create Date: 2026-03-02 15:04:15.246343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5c6394b7b8'
down_revision: Union[str, Sequence[str], None] = 'ff3b5efad75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoption_listings', sa.Column('is_vaccinated', sa.Boolean(), nullable=True))
    op.add_column('adoption_listings', sa.Column('is_sterilized', sa.Boolean(), nullable=True))
    op.add_column('adoption_listings', sa.Column('is_dewormed', sa.Boolean(), nullable=True))
    op.add_column('adoption_listings', sa.Column('temperament', sa.Text(), nullable=True))
    op.add_column('adoption_listings', sa.Column('energy_level', sa.String(), nullable=True))
    op.add_column('adoption_listings', sa.Column('social_cats', sa.Boolean(), nullable=True))
    op.add_column('adoption_listings', sa.Column('social_dogs', sa.Boolean(), nullable=True))
    op.add_column('adoption_listings', sa.Column('social_children', sa.Boolean(), nullable=True))
    op.add_column('adoption_listings', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('adoption_listings', sa.Column('microchip_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adoption_listings', 'microchip_number')
    op.drop_column('adoption_listings', 'weight_kg')
    op.drop_column('adoption_listings', 'social_children')
    op.drop_column('adoption_listings', 'social_dogs')
    op.drop_column('adoption_listings', 'social_cats')
    op.drop_column('adoption_listings', 'energy_level')
    op.drop_column('adoption_listings', 'temperament')
    op.drop_column('adoption_listings', 'is_dewormed')
    op.drop_column('adoption_listings', 'is_sterilized')
    op.drop_column('adoption_listings', 'is_vaccinated')
    # ### end Alembic commands ###
