"""Sync schema updates

Revision ID: b285925dc51c
Revises: b9749d8787dd
Create Date: 2026-03-02 11:06:26.096039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b285925dc51c'
down_revision: Union[str, Sequence[str], None] = 'b9749d8787dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_listings',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('published_by', sa.String(length=36), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('adopted_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_listings_published_by'), 'adoption_listings', ['published_by'], unique=False)
    op.add_column('adoption_requests', sa.Column('listing_id', sa.String(length=36), nullable=False))
    op.add_column('adoption_requests', sa.Column('applicant_name', sa.String(length=255), nullable=True))
    op.add_column('adoption_requests', sa.Column('house_type', sa.String(length=100), nullable=True))
    op.add_column('adoption_requests', sa.Column('has_yard', sa.Boolean(), nullable=True))
    op.add_column('adoption_requests', sa.Column('own_or_rent', sa.String(length=50), nullable=True))
    op.add_column('adoption_requests', sa.Column('landlord_permission', sa.Boolean(), nullable=True))
    op.add_column('adoption_requests', sa.Column('other_pets', sa.Text(), nullable=True))
    op.add_column('adoption_requests', sa.Column('has_children', sa.Boolean(), nullable=True))
    op.add_column('adoption_requests', sa.Column('children_ages', sa.String(length=100), nullable=True))
    op.add_column('adoption_requests', sa.Column('hours_alone', sa.Integer(), nullable=True))
    op.add_column('adoption_requests', sa.Column('financial_commitment', sa.Boolean(), nullable=True))
    op.add_column('adoption_requests', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('adoption_requests', sa.Column('previous_experience', sa.Text(), nullable=True))
    op.create_index(op.f('ix_adoption_requests_listing_id'), 'adoption_requests', ['listing_id'], unique=False)
    op.drop_constraint(op.f('adoption_requests_pet_id_fkey'), 'adoption_requests', type_='foreignkey')
    op.drop_column('adoption_requests', 'pet_id')
    op.drop_column('adoption_requests', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoption_requests', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('adoption_requests', sa.Column('pet_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('adoption_requests_pet_id_fkey'), 'adoption_requests', 'pets', ['pet_id'], ['id'])
    op.drop_index(op.f('ix_adoption_requests_listing_id'), table_name='adoption_requests')
    op.drop_column('adoption_requests', 'previous_experience')
    op.drop_column('adoption_requests', 'reason')
    op.drop_column('adoption_requests', 'financial_commitment')
    op.drop_column('adoption_requests', 'hours_alone')
    op.drop_column('adoption_requests', 'children_ages')
    op.drop_column('adoption_requests', 'has_children')
    op.drop_column('adoption_requests', 'other_pets')
    op.drop_column('adoption_requests', 'landlord_permission')
    op.drop_column('adoption_requests', 'own_or_rent')
    op.drop_column('adoption_requests', 'has_yard')
    op.drop_column('adoption_requests', 'house_type')
    op.drop_column('adoption_requests', 'applicant_name')
    op.drop_column('adoption_requests', 'listing_id')
    op.drop_index(op.f('ix_adoption_listings_published_by'), table_name='adoption_listings')
    op.drop_table('adoption_listings')
    # ### end Alembic commands ###
