"""add_digital_prescriptions

Revision ID: 2e60e3dc2054
Revises: 8950f1cdd223
Create Date: 2026-03-04 17:37:05.569678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e60e3dc2054'
down_revision: Union[str, Sequence[str], None] = '8950f1cdd223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('veterinarian_id', sa.String(), nullable=True))
    op.add_column('medical_records', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('medical_records', sa.Column('reason_for_visit', sa.String(), server_default='No especificado', nullable=False))
    op.add_column('medical_records', sa.Column('treatment', sa.Text(), nullable=True))
    op.add_column('medical_records', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('medical_records', 'clinic_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medical_records', 'appointment_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('medical_records', 'diagnosis',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    op.drop_index(op.f('ix_medical_records_appointment_id'), table_name='medical_records')
    op.create_index(op.f('ix_medical_records_appointment_id'), 'medical_records', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_medical_records_id'), 'medical_records', ['id'], unique=False)
    op.create_index(op.f('ix_medical_records_veterinarian_id'), 'medical_records', ['veterinarian_id'], unique=False)
    op.drop_constraint(op.f('medical_records_clinic_id_fkey'), 'medical_records', type_='foreignkey')
    op.drop_constraint(op.f('medical_records_appointment_id_fkey'), 'medical_records', type_='foreignkey')
    op.drop_constraint(op.f('medical_records_vet_id_fkey'), 'medical_records', type_='foreignkey')
    op.drop_column('medical_records', 'updated_at')
    op.drop_column('medical_records', 'created_at')
    op.drop_column('medical_records', 'clinical_notes')
    op.drop_column('medical_records', 'vet_id')
    op.create_index(op.f('ix_medication_reminders_id'), 'medication_reminders', ['id'], unique=False)
    op.drop_column('medication_reminders', 'updated_at')
    op.drop_column('medication_reminders', 'created_at')
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.drop_column('prescriptions', 'updated_at')
    op.drop_column('prescriptions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('prescriptions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.add_column('medication_reminders', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('medication_reminders', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_medication_reminders_id'), table_name='medication_reminders')
    op.add_column('medical_records', sa.Column('vet_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('clinical_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('medical_records_vet_id_fkey'), 'medical_records', 'veterinarians', ['vet_id'], ['id'])
    op.create_foreign_key(op.f('medical_records_appointment_id_fkey'), 'medical_records', 'appointments', ['appointment_id'], ['id'])
    op.create_foreign_key(op.f('medical_records_clinic_id_fkey'), 'medical_records', 'clinics', ['clinic_id'], ['id'])
    op.drop_index(op.f('ix_medical_records_veterinarian_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_appointment_id'), table_name='medical_records')
    op.create_index(op.f('ix_medical_records_appointment_id'), 'medical_records', ['appointment_id'], unique=True)
    op.alter_column('medical_records', 'diagnosis',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('medical_records', 'appointment_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('medical_records', 'clinic_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('medical_records', 'notes')
    op.drop_column('medical_records', 'treatment')
    op.drop_column('medical_records', 'reason_for_visit')
    op.drop_column('medical_records', 'date')
    op.drop_column('medical_records', 'veterinarian_id')
    # ### end Alembic commands ###
