name: Deploy Backend to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [core, adopciones, mascotas, perdidas, carnet, directorio, ecommerce]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Secrets (Check if set)
      run: |
        if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          echo "Error: AWS_ACCESS_KEY_ID is NOT set in GitHub Secrets"
          exit 1
        else
          echo "AWS_ACCESS_KEY_ID is found"
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and Package
      run: |
        cd backend/michicondrias_${{ matrix.service }}
        # Instalar dependencias usando la imagen oficial de Amazon Linux para evitar errores de GLIBC_2.28
        docker run --rm -v ${{ github.workspace }}/backend/michicondrias_${{ matrix.service }}:/var/task public.ecr.aws/sam/build-python3.11 pip install -r requirements.txt -t .
        # Comprimir el código y las dependencias ya compatibles con Lambda
        zip -r ../../${{ matrix.service }}.zip .

    - name: Upload to S3
      run: |
        aws s3 cp ${{ matrix.service }}.zip s3://michicondrias-storage-1/deployments/${{ matrix.service }}.zip

    - name: Deploy to AWS Lambda (via S3)
      run: |
        aws lambda update-function-code \
          --function-name michicondrias-${{ matrix.service }} \
          --s3-bucket michicondrias-storage-1 \
          --s3-key deployments/${{ matrix.service }}.zip
