"""Sync schema updates

Revision ID: 78b251b61fc6
Revises: 6cbb8d9b9ab4
Create Date: 2026-03-02 11:06:19.740892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b251b61fc6'
down_revision: Union[str, Sequence[str], None] = '6cbb8d9b9ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('id_front_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('id_back_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('proof_of_address_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'proof_of_address_url')
    op.drop_column('users', 'id_back_url')
    op.drop_column('users', 'id_front_url')
    op.drop_column('users', 'verification_status')
    # ### end Alembic commands ###
